version: '3.8'

services:

  santa:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_thing
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - 8500:8000
    environment:
      PYTHONUNBUFFERED: 1
      HOSTNAME: santamark4u
    restart: unless-stopped



